# CI de Nível 03 - Disparo após a conclusão de um pipeline

# nome do nosso 'pipeline'
name: 'Execução por Deploy'

# regras de disparo (gatilhos/triggers)
# gatilho de exec a partir de outro pipeline = workflow_run
on:
  workflow_run:
    workflows: ['Execução Manual']
    types:
      - completed

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:

    # Máquina que o job vai executar
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion ==  'success' }}

    # Passos do script de build
    steps:
    # Clone do projeto
    - name: Clonar projeto
      uses: actions/checkout@v4

    # Instalação do NodeJs
    - name: Instalar NodeJs
      uses: actions/setup-node@v3
      with:
        node-version: 22.x

    # Instalação do Yarn
    - name: Instalar Yarn
      run: npm install -g yarn

    # Instalação das dependências
    - name: Instalar dependências
      run: yarn

    # Instalação do Playwright
    - name: Instalar Playwright
      run: yarn playwright install

    # Executar os testes e2e
    - name: Executar Testes E2E
      run: yarn run e2e

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      # if: ${{ always() }}
      with:
        name: relatorio
        path: ./playwright-report